/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.awt.Component;
import java.awt.Container;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import javax.swing.text.DefaultEditorKit;
import javax.swing.text.JTextComponent;

/**
 *
 * @author xboxc
 */
public class JMain extends javax.swing.JFrame {

    /**
     * Creates new form JMain
     */
    private String texto="";
    public JMain() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pop_acoes = new javax.swing.JPopupMenu();
        mitem_copia = new javax.swing.JMenuItem();
        mitem_cola = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        texta_copia = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        texta_cola = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        mitem_copia.setText("Copiar");
        mitem_copia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mitem_copia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mitem_copiaMouseClicked(evt);
            }
        });
        pop_acoes.add(mitem_copia);

        mitem_cola.setText("Colar");
        mitem_cola.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mitem_cola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mitem_colaMouseClicked(evt);
            }
        });
        pop_acoes.add(mitem_cola);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        texta_copia.setEditable(false);
        texta_copia.setColumns(20);
        texta_copia.setRows(5);
        texta_copia.setText("O rato roeu a roupa do rei de roma!");
        texta_copia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texta_copiaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(texta_copia);

        jLabel1.setText("Copie e Cole o texto abaixo");

        texta_cola.setColumns(20);
        texta_cola.setRows(5);
        texta_cola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texta_colaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(texta_cola);

        jLabel2.setText("Cole aqui");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jLabel2))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texta_copiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texta_copiaMouseClicked
        if(evt.getButton() == MouseEvent.BUTTON3){
            pop_acoes.setLocation(evt.getXOnScreen(), evt.getYOnScreen());
            pop_acoes.setVisible(true);
        }else{
            pop_acoes.setVisible(false);
        }
    }//GEN-LAST:event_texta_copiaMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        pop_acoes.setVisible(false);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void texta_colaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texta_colaMouseClicked
        if(evt.getButton() == MouseEvent.BUTTON3){
            pop_acoes.setLocation(evt.getXOnScreen(), evt.getYOnScreen());
            pop_acoes.setVisible(true);
        }else{
            pop_acoes.setVisible(false);
        }
    }//GEN-LAST:event_texta_colaMouseClicked

    private void mitem_copiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mitem_copiaMouseClicked
        if(evt.getButton() == MouseEvent.BUTTON1){
            mitem_copia.setText("Copiado!");
        }else{
            mitem_copia.setText("Copiar");
        }
    }//GEN-LAST:event_mitem_copiaMouseClicked

    private void mitem_colaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mitem_colaMouseClicked
        if(evt.getButton() == MouseEvent.BUTTON1){
            mitem_cola.setText("Colado!");
        }else{
            mitem_cola.setText("Colar");
        }
    }//GEN-LAST:event_mitem_colaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem mitem_cola;
    private javax.swing.JMenuItem mitem_copia;
    private javax.swing.JPopupMenu pop_acoes;
    private javax.swing.JTextArea texta_cola;
    private javax.swing.JTextArea texta_copia;
    // End of variables declaration//GEN-END:variables
}
